source(here::here("tests/r/test_statsmodels_quantreg.R"))
source(here::here("tests/r/test_statsmodels_probit.R"))
source(here::here("tests/r/test_statsmodels_logit.R"))
source(here::here("tests/r/test_statsmodels_poisson.R"))
source(here::here("tests/r/test_statsmodels_wls.R"))
source(here::here("tests/r/test_statsmodels_mnlogit.R"))