name: CI Testing

on:
  workflow_dispatch:
  workflow_call:

jobs:
  unit-tests:
    strategy:
      fail-fast: true
      matrix:
        python:
          - "3.11"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python v${{ matrix.python}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: false

      - name: Install dependencies
        run: |
          poetry install --with=dev

      - name: Run pytest
        run: |
          pytest
